server:
  port: 8082

spring:
  datasource: jdbc:h2:mem:customersdb
  driverClassName: org.h2.Driver
  username: sa
  password:

jpa:
  hibernate:
    ddl-auto: create

h2:
  console:
    enabled: true
